name: upver

on:
  pull_request:
    branches:
      - alpha
    types: [closed]

jobs:
  upver:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repo
        uses: actions/checkout@v2
      - name: Checkout fuyutarow/upver as a CI tool
        uses: actions/checkout@v2
        with:
          repository: fuyutarow/upver
          path: upver
      - name: Config git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      - name: Update version
        run: |
          upver/bin/musl/upver up -rz next/package.json
          VERSION=$(upver/bin/musl/upver show --core next/package.json)
          git commit -am "[GitHub Actions] Update to v${VERSION}"
          git push
      - name: Release with tag
        run: |
          VERSION=$(upver/bin/musl/upver show --core next/package.json)
          git tag v${VERSION}
          git push --tags
      - name: Create a branch and push it to deploy to Vercel
        run: |
          VERSION=$(upver/bin/musl/upver show --core next/package.json)
          VERSION_without_dots=$(echo ${VERSION} | sed 's/\.//g')
          git switch -c ${VERSION}
          ( echo https://adskita-git-${VERSION_without_dots}.fuyutarow.vercel.app && cat README.md ) > temp && mv temp README.md
          git commit -am "[GitHub Actions] Push it to deploy to Vercel"
          git push --set-upstream origin ${VERSION}
